
export const confrimOrderTemplate = {
  enabled: false,
  subject: "Delivery update for order {order}",
  font: "inherit",
  storeName: "preorderstore",
  storeNameBold: true,
  storeNameColor: "#333333",
  storeNameFontSize: "28",
  subheading: "WE’VE GOT YOUR PREORDER",
  subheadingFontSize: "18",
  subheadingColor: "#333333",
  subheadingBold: true,
  description: "Your order {order} contains preorder items. We will deliver them as soon as they become available and will notify you once your order has been shipped.",
  descriptionFontSize: "14",
  descriptionColor: "#333333",
  descriptionBold: false,
  productTitleFontSize: "16",
  productTitleColor: "#333333",
  productTitleBold: true,
  preorderText: "Preorder",
  fullPaymentText: "Full Payment",
  partialPaymentText: "Partial Payment",
  paymentTextFontSize: "14",
  paymentTextColor: "#333333",
  paymentTextBold: false,
  showCancelButton: true,
  cancelButtonStyle: "solid",
  cancelButtonText: "Cancel order {order}",
  cancelButtonFontSize: "14",
  cancelButtonTextColor: "#ffffff",
  cancelButtonBold: false,
  cancelButtonBackgroundColor: "#757575",
  cancelButtonBorderSize: "1",
  cancelButtonBorderColor: "#3d3d3d",
  cancelButtonGradientDegree: "90",
  cancelButtonGradientColor1: "#757575",
  cancelButtonGradientColor2: "#a0a0a0",
  cancelButtonBorderRadius: "8"
}

export const ShippingEmailTemplate = {
  enabled: false,
  subject: "Delivery update for order {order}",
  font: "inherit",
  storeName: "preorderstore",
  storeNameBold: true,
  storeNameColor: "#333333",
  storeNameFontSize: "28",
  subheading: "WE’VE GOT YOUR PREORDER",
  subheadingFontSize: "18",
  subheadingColor: "#333333",
  subheadingBold: true,
  description: "Your order {order} contains preorder items. We will deliver them as soon as they become available and will notify you once your order has been shipped.",
  descriptionFontSize: "14",
  descriptionColor: "#333333",
  descriptionBold: false,
  productTitleFontSize: "16",
  productTitleColor: "#333333",
  productTitleBold: true,
  preorderText: "Preorder",
  fullPaymentText: "Full Payment",
  partialPaymentText: "Partial Payment",
  paymentTextFontSize: "14",
  paymentTextColor: "#333333",
  paymentTextBold: false,
  showCancelButton: true,
  cancelButtonStyle: "solid",
  cancelButtonText: "Cancel order {order}",
  cancelButtonFontSize: "14",
  cancelButtonTextColor: "#ffffff",
  cancelButtonBold: false,
  cancelButtonBackgroundColor: "#757575",
  cancelButtonBorderSize: "1",
  cancelButtonBorderColor: "#3d3d3d",
  cancelButtonGradientDegree: "90",
  cancelButtonGradientColor1: "#757575",
  cancelButtonGradientColor2: "#a0a0a0",
  cancelButtonBorderRadius: "8"
}
