api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "preorder-validation"
type = "function"
uid = "727816d3-e3d1-6137-2a1c-9335d42a34a017d7acde"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
