-- CreateTable
CREATE TABLE "EmailSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shopId" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "subject" TEXT NOT NULL DEFAULT 'Delivery update for order {order}',
    "font" TEXT NOT NULL DEFAULT 'inherit',
    "storeName" TEXT NOT NULL DEFAULT 'preorderstore',
    "storeNameBold" BOOLEAN NOT NULL DEFAULT true,
    "storeNameColor" TEXT NOT NULL DEFAULT '#333333',
    "storeNameFontSize" TEXT NOT NULL DEFAULT '28',
    "subheading" TEXT NOT NULL DEFAULT 'WE’VE GOT YOUR PREORDER',
    "subheadingFontSize" TEXT NOT NULL DEFAULT '18',
    "subheadingColor" TEXT NOT NULL DEFAULT '#333333',
    "subheadingBold" BOOLEAN NOT NULL DEFAULT true,
    "description" TEXT NOT NULL DEFAULT 'Your order {order} contains preorder items. We will deliver them as soon as they become available and will notify you once your order has been shipped.',
    "descriptionFontSize" TEXT NOT NULL DEFAULT '14',
    "descriptionColor" TEXT NOT NULL DEFAULT '#333333',
    "descriptionBold" BOOLEAN NOT NULL DEFAULT false,
    "productTitleFontSize" TEXT NOT NULL DEFAULT '16',
    "productTitleColor" TEXT NOT NULL DEFAULT '#333333',
    "productTitleBold" BOOLEAN NOT NULL DEFAULT true,
    "preorderText" TEXT NOT NULL DEFAULT 'Preorder',
    "fullPaymentText" TEXT NOT NULL DEFAULT 'Full Payment',
    "partialPaymentText" TEXT NOT NULL DEFAULT 'Partial Payment',
    "paymentTextFontSize" TEXT NOT NULL DEFAULT '14',
    "paymentTextColor" TEXT NOT NULL DEFAULT '#333333',
    "paymentTextBold" BOOLEAN NOT NULL DEFAULT false,
    "showCancelButton" BOOLEAN NOT NULL DEFAULT true,
    "cancelButtonStyle" TEXT NOT NULL DEFAULT 'solid',
    "cancelButtonText" TEXT NOT NULL DEFAULT 'Cancel order {order}',
    "cancelButtonFontSize" TEXT NOT NULL DEFAULT '14',
    "cancelButtonTextColor" TEXT NOT NULL DEFAULT '#ffffff',
    "cancelButtonBold" BOOLEAN NOT NULL DEFAULT false,
    "cancelButtonBackgroundColor" TEXT NOT NULL DEFAULT '#757575',
    "cancelButtonBorderSize" TEXT NOT NULL DEFAULT '1',
    "cancelButtonBorderColor" TEXT NOT NULL DEFAULT '#3d3d3d',
    "cancelButtonGradientDegree" TEXT NOT NULL DEFAULT '90',
    "cancelButtonGradientColor1" TEXT NOT NULL DEFAULT '#757575',
    "cancelButtonGradientColor2" TEXT NOT NULL DEFAULT '#a0a0a0',
    "cancelButtonBorderRadius" TEXT NOT NULL DEFAULT '8',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "EmailSettings_shopId_key" ON "EmailSettings"("shopId");
